name = "VanillaWorld"
uuid = "890a6884-3078-43a5-8445-0f7842e240aa"
authors = ["Jun Tian <tianjun.cpp@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
